server:
  port: 6060

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_monitor_agent_4j?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      pool-name: DataSourceHikariCP
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 18000000
      connection-test-query: SELECT 1

translate:
  url: ${TRANSLATE_URL}
  appId: ${TRANSLATE_APP_ID}
  secretKey: ${TRANSLATE_SECRET_KEY}

dingTalk:
  url: ${DING_TALK_URL}
  robotToken: ${DING_TALK_ROBOT_TOKEN}
  secretKey: ${DING_TALK_SECRET_KEY}