spring:
  application:
    name: stock-monitor-web
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      timeout: 5000
      port: 6379
      database: 0

mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_empty
  mapper-locations: classpath*:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info