server:
  port: 6061

spring:
  ai:
    mcp:
      server:
        name: stock-monitor-mcp-server
        version: 1.0.0
        sse-endpoint: /sse
        type: async
  mail:
    host: smtp.163.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 25
    default-encoding: UTF-8
    protocol: smtp
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_monitor_agent_4j?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      pool-name: DataSourceHikariCP
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 18000000
      connection-test-query: SELECT 1